package vip.gg.community.demo.model;

public class UserAuth {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.id
     *
     * @mbg.generated Sat Jul 04 18:33:04 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.account_id
     *
     * @mbg.generated Sat Jul 04 18:33:04 CST 2020
     */
    private String accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.name
     *
     * @mbg.generated Sat Jul 04 18:33:04 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.token
     *
     * @mbg.generated Sat Jul 04 18:33:04 CST 2020
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.gmt_create
     *
     * @mbg.generated Sat Jul 04 18:33:04 CST 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.gmt_modified
     *
     * @mbg.generated Sat Jul 04 18:33:04 CST 2020
     */
    private Long gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.bio
     *
     * @mbg.generated Sat Jul 04 18:33:04 CST 2020
     */
    private String bio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.avatar_url
     *
     * @mbg.generated Sat Jul 04 18:33:04 CST 2020
     */
    private String avatarUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.auth_type
     *
     * @mbg.generated Sat Jul 04 18:33:04 CST 2020
     */
    private String authType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.user_id
     *
     * @mbg.generated Sat Jul 04 18:33:04 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.password
     *
     * @mbg.generated Sat Jul 04 18:33:04 CST 2020
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auth.id
     *
     * @return the value of user_auth.id
     *
     * @mbg.generated Sat Jul 04 18:33:04 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auth.id
     *
     * @param id the value for user_auth.id
     *
     * @mbg.generated Sat Jul 04 18:33:04 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auth.account_id
     *
     * @return the value of user_auth.account_id
     *
     * @mbg.generated Sat Jul 04 18:33:04 CST 2020
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auth.account_id
     *
     * @param accountId the value for user_auth.account_id
     *
     * @mbg.generated Sat Jul 04 18:33:04 CST 2020
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auth.name
     *
     * @return the value of user_auth.name
     *
     * @mbg.generated Sat Jul 04 18:33:04 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auth.name
     *
     * @param name the value for user_auth.name
     *
     * @mbg.generated Sat Jul 04 18:33:04 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auth.token
     *
     * @return the value of user_auth.token
     *
     * @mbg.generated Sat Jul 04 18:33:04 CST 2020
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auth.token
     *
     * @param token the value for user_auth.token
     *
     * @mbg.generated Sat Jul 04 18:33:04 CST 2020
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auth.gmt_create
     *
     * @return the value of user_auth.gmt_create
     *
     * @mbg.generated Sat Jul 04 18:33:04 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auth.gmt_create
     *
     * @param gmtCreate the value for user_auth.gmt_create
     *
     * @mbg.generated Sat Jul 04 18:33:04 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auth.gmt_modified
     *
     * @return the value of user_auth.gmt_modified
     *
     * @mbg.generated Sat Jul 04 18:33:04 CST 2020
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auth.gmt_modified
     *
     * @param gmtModified the value for user_auth.gmt_modified
     *
     * @mbg.generated Sat Jul 04 18:33:04 CST 2020
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auth.bio
     *
     * @return the value of user_auth.bio
     *
     * @mbg.generated Sat Jul 04 18:33:04 CST 2020
     */
    public String getBio() {
        return bio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auth.bio
     *
     * @param bio the value for user_auth.bio
     *
     * @mbg.generated Sat Jul 04 18:33:04 CST 2020
     */
    public void setBio(String bio) {
        this.bio = bio == null ? null : bio.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auth.avatar_url
     *
     * @return the value of user_auth.avatar_url
     *
     * @mbg.generated Sat Jul 04 18:33:04 CST 2020
     */
    public String getAvatarUrl() {
        return avatarUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auth.avatar_url
     *
     * @param avatarUrl the value for user_auth.avatar_url
     *
     * @mbg.generated Sat Jul 04 18:33:04 CST 2020
     */
    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl == null ? null : avatarUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auth.auth_type
     *
     * @return the value of user_auth.auth_type
     *
     * @mbg.generated Sat Jul 04 18:33:04 CST 2020
     */
    public String getAuthType() {
        return authType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auth.auth_type
     *
     * @param authType the value for user_auth.auth_type
     *
     * @mbg.generated Sat Jul 04 18:33:04 CST 2020
     */
    public void setAuthType(String authType) {
        this.authType = authType == null ? null : authType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auth.user_id
     *
     * @return the value of user_auth.user_id
     *
     * @mbg.generated Sat Jul 04 18:33:04 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auth.user_id
     *
     * @param userId the value for user_auth.user_id
     *
     * @mbg.generated Sat Jul 04 18:33:04 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auth.password
     *
     * @return the value of user_auth.password
     *
     * @mbg.generated Sat Jul 04 18:33:04 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auth.password
     *
     * @param password the value for user_auth.password
     *
     * @mbg.generated Sat Jul 04 18:33:04 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}